#!/usr/bin/env python3
"""ADR-2026-30 — Branded PDF Requirement (Superseded by SOP-001)"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from lib.greenmark_pdf import *

OUTPUT = DOCS_ROOT / "adrs" / "ADR-2026-30-adr-format-requires-branded-pdf.pdf"


def content(story, p):
    story.append(BrandHeader(USABLE, "ADR-2026-30", "All ADRs Require a Branded PDF"))
    story.append(Spacer(1, 10))
    story.append(p("<b>Status:</b> Superseded by SOP-001  |  <b>Date:</b> 2026-03-11  |  "
                   "<b>Owner:</b> Daniel Shanklin", META))
    story.append(Spacer(1, 6))

    story.append(AccentBox(USABLE,
                           "SUPERSEDED: This ADR has been absorbed into SOP-001 (Creating ADRs and SOPs). "
                           "The branded PDF requirement is now part of the unified document creation procedure.",
                           bg=AMBER_BG, border=AMBER_BORDER, text_color=AMBER))
    story.append(Spacer(1, 6))

    story.append(p("BLUF (Bottom Line Up Front)", H2))
    story.append(p(
        "Every ADR must ship with a branded PDF generated by a co-located Python script using ReportLab. "
        "This requirement is now consolidated into SOP-001 alongside the BLUF requirement (ADR-2026-05)."))
    story.append(Spacer(1, 6))

    story.append(p("Original Decision", H2))
    story.append(p(
        "Every ADR must include a branded PDF using the Greenmark brand system (dark green header, logo, "
        "branded tables, accent boxes). Generator scripts are version-controlled alongside the markdown."))
    story.append(hr())
    story.append(p("See SOP-001 for the current, consolidated procedure including brand constants and PDF spec.", META))


if __name__ == "__main__":
    build_doc(OUTPUT, "ADR-2026-30: Branded PDF Requirement (Superseded)", content)
